Ot124 26
alkemyTech/OT124-CLIENT pull request #35
Opened 2022-02-08 00:28 UTC by juanpa0011

"/mi-perfil"
Dos rutas creadas pero sin data enviada o para cargar.
Actualmente no puede cargar imágenes, tampoco lo pide la actividad, pero supongo que se puede tomar lo que hizo Diego y replicarlo. (Para adaptar luego en issues)

2022-02-08 21:16 UTC, FrancoMartinPersonal reviewed
lo único es que no se que pasa en el package json, no se si se tendrá que reparar pero yo lo apruebo

2022-02-08 21:16 UTC, FrancoMartinPersonal approved these changes

2022-02-09 18:25 UTC, rafalynch requested changes

2022-02-09 18:25 UTC, rafalynch commented on package.json
> +<<<<<<< HEAD
Ojo con estas lineas que quedan del merge

2022-02-09 18:25 UTC, rafalynch commented on src/components/CUNewsForm.js
>    console.log(aNew);
```suggestion
  
```

2022-02-10 11:47 UTC, dhsosa98 approved these changes

2022-02-10 11:48 UTC, merged