Ot124 50
alkemyTech/OT124-CLIENT pull request #40
Opened 2022-02-08 03:56 UTC by FrancoMartinPersonal

dejé un mensaje escrito advirtiendo que se necesita los endpoints necesarios para que estos componentes de editar organización funcionen correctamente, cualquier cosa una vez realizados o necesitados, informarme que los edito

2022-02-09 18:48 UTC, rafalynch requested changes

2022-02-09 18:48 UTC, rafalynch commented on src/App.js
> -import BackofficeHome from "./pages/backoffice";
Franco, esta linea creo que no deberia ser borrada.

2022-02-09 18:48 UTC, rafalynch commented on src/App.js
> -          <Route index element={<BackofficeHome />} />
Esta linea tampoco deberia borrarse

2022-02-09 18:48 UTC, rafalynch commented on src/components/BackOfficeAdminLayout.js
> +import BackOfficeCard from "./BackofficeCard";
```suggestion
import BackOfficeCard from "./BackOfficeCard";
```

2022-02-14 22:36 UTC, panchoarc approved these changes

2022-02-14 23:24 UTC, rafalynch approved these changes

2022-02-14 23:25 UTC, merged