Private and admin routes - Ot124 103
alkemyTech/OT124-CLIENT pull request #43
Opened 2022-02-09 17:52 UTC by rafalynch

## Summary

- Added PrivateRoute and AdminRoute components for secure routing.

2022-02-09 22:01 UTC, FrancoMartinPersonal approved these changes

2022-02-10 11:59 UTC, dhsosa98 requested changes
Rafa ya tienes el usuario en redux, así que ya puedes usar un useSelector y traerte su rol

2022-02-10 16:49 UTC, rafalynch commented
Implementado el sistema de roles

2022-02-10 19:15 UTC, dhsosa98 approved these changes

2022-02-10 19:19 UTC, merged