Fixed news backOffice components, reestructure Categories & Created new DeleteAlert -  Ot124 64
alkemyTech/OT124-CLIENT pull request #47
Opened 2022-02-10 10:20 UTC by dhsosa98

### Summary

2022-02-10 11:42 UTC, juanpa0011 requested changes

2022-02-10 11:42 UTC, juanpa0011 commented on src/components/CUNewsForm.js
>    console.log(aNew);
I found a console.log

Destroy, destroy, destroy...

2022-02-10 11:42 UTC, juanpa0011 commented on src/components/CategoriesHeader.js
> +          className=" bg-green-600 text-sm sm:text-base text-white shadow shadow-green-800 rounded-sm px-8 py-4 hover:bg-green-700 transform ease-in-out duration-300 hover:scale-105"
No se si es muy importante, pero la gama de los colores que estamos usando para las bg son las 500 tirando a 600 con hover. Por ahi en el caso del verde queda mejor con 600 a 700. Lo dejo a tu criterio :P

2022-02-10 11:54 UTC, dhsosa98 commented on src/components/CUNewsForm.js
>    console.log(aNew);
Fixed

2022-02-10 11:57 UTC, dhsosa98 commented on src/components/CategoriesHeader.js
> +          className=" bg-green-600 text-sm sm:text-base text-white shadow shadow-green-800 rounded-sm px-8 py-4 hover:bg-green-700 transform ease-in-out duration-300 hover:scale-105"
Che, eso de la gama hay que ponernos de acuerdo jajaja, yo puse para que quedara bien no más, pero sí, tiene todo que seguir una misma estructura. Hoy lo hablamos en la daily. Igual ningún diseño se debería quedar como está, lo importante ahora es la funcionalidad

2022-02-10 16:11 UTC, rafalynch requested changes
Te dejo lo mismo que en el otro PR, las rutas de novedades pueden ir dentro de la ruta "novedades".

2022-02-10 16:11 UTC, rafalynch commented on src/components/CUNewsForm.js
>          console.log(err);
```suggestion
        
```

2022-02-10 16:11 UTC, rafalynch commented on src/pages/backoffice/categories/BackofficeCategories.js
> +        console.log(err);
```suggestion
        
```

2022-02-12 11:55 UTC, dhsosa98 commented on src/pages/backoffice/categories/BackofficeCategories.js
> +        console.log(err);
Resuelto

2022-02-12 12:26 UTC, juanpa0011 approved these changes

2022-02-12 21:05 UTC, rafalynch approved these changes

2022-02-12 21:05 UTC, merged